feat: 지원 및 질문 조회 API 추가
gdsc-uos-branding/server pull request #11
Opened 2023-03-15 03:33 UTC by pasly0920

### Description

- Introduction 조회 API 추가
- 지원서 조회, 제출 API 추가

### 특이사항

- Application.yml 업데이트 하였습니다 참고 바랍니다.

2023-03-15 05:38 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/api/IntroductionApi.java
> +    public ResponseEntity<IntroductionGetResponse> getTeamIntroduction(@PathVariable Team team) {
[Nit] 파라미터로 enum 값이 들어가다보니 프론트 호출 시 어색하게 느낄 수도 있지 않을까요? 저도 어드민 쪽 구현하다가 team보단 teamId를 반환하게끔하면 좋지않을까 싶어요 ! 또한, common 팀의 경우, jpa를 사용해서 해당 값으로 팀의 정보를 불러오는 것은 +1과 같은 로직도 필요해지니 인지하시고 계시면 괜찮지만, 인수인계 시에 추가적인 설명이 필요할 것 같아요 !

2023-03-15 05:44 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/dto/IntroductionGetResponse.java
> +    @Builder
빌더 패턴 아주 좋아요 !

2023-03-15 05:47 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/service/IntroductionService.java
> +        if (intro == null) {
@pasly0920 intro를 가져왔을 때 about/activity/target 중에 하나라도 내용이 비어있는 경우에 대해선 따로 처리할 필요가 없겠죠?

2023-03-15 05:48 UTC, iju1633 requested changes
[Nit] 부분과 introduction을 불러왔을 때 null이 아니지만 about/activity/target 중 하나 혹은 두 개가 비어있는 경우에 대한 핸들 관련 comment 남겼습니다 !

2023-03-15 06:07 UTC, pasly0920 commented on src/main/java/com/gdscuos/recruit/domain/applicant/service/IntroductionService.java
> +        if (intro == null) {
그 경우에는 애초에 데이터가 잘못된 거라서 따로  처리하지 않아도 괜찮을 것 같습니다.

2023-03-15 06:10 UTC, pasly0920 commented on src/main/java/com/gdscuos/recruit/domain/applicant/api/IntroductionApi.java
> +    public ResponseEntity<IntroductionGetResponse> getTeamIntroduction(@PathVariable Team team) {
@iju1633 이 부분은 저도 고민을 했는데, team_id로 부르는 것도 괜찮긴하지만 id와 team이 이어지는 부분이 부족하다고 느껴져서, 그나마 가독성을 높이려면 String으로 위처럼 받아오는 게 괜찮다고 생각했는데 어떠신가여

2023-03-15 06:11 UTC, pasly0920 commented
아직 작업이 끝나지 않아서 천천히 봐주셔도 괜찮은데 감사합니다

2023-03-15 06:30 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/api/IntroductionApi.java
> +    public ResponseEntity<IntroductionGetResponse> getTeamIntroduction(@PathVariable Team team) {
@pasly0920 생각해보셨던 부분이군요 ! 좋습니다ㅎㅎ 말씀해주신대로 teamId 또한 모호하다고 느껴져서 String 값을 받아오는 것으로 해봅시다 ! 저도 지금과 같이 통일시켜서 작업해볼게요 !

2023-03-19 05:38 UTC, pasly0920 commented
@iju1633 작업 끝입니다.. 중간에 로직을 업데이트를 하기도 해서 사이즈가 많이 커졌네요. Notion에서 Logic 업데이트 관련 기록을 남겨두었습니다.

2023-03-21 05:23 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/api/ApplicationApi.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("");
@pasly0920 response할 body가 없는게 의도라면 `ResponseEntity.status(HttpStatus.CREATED).build(); 이렇게 하시면 됩니다 !

2023-03-21 05:24 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/dao/ApplicationQuestionFindDao.java
> +public class ApplicationQuestionFindDao {
[Nit] 추후에 이해를 위해 파일별 주석을 달아주시는 것은 어떨까요?

2023-03-21 05:26 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/dao/ApplicationTeamQuestionFindDao.java
> +                    .where(application.user.id.eq(5L), applicationQuestion.team.eq(team))
@pasly0920 user id 값이 5라 되어있는데 특정 유저의 질문만 가져오는 게 되는 것일까요?

혹시 그게 아니라면 상수로 관리하는 게 이해하기 더 좋을 것 같아요

2023-03-21 05:30 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/global/config/SecurityConfig.java
> +                        authService); // userService()은 소셜 로그인 성공 시 후속 조치를 진행할 UserService 인터페이스의 구현체를 등록
[Nit] 주석때문에 길이가 길어져 자동정렬하면서 개행이 추가되었는데 수정해주셔도 좋을 것 같아요 !

2023-03-21 05:31 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/global/error/exception/ErrorCode.java
> +    EMAIL_DUPLICATION("U03", "Email is Duplicated.", HttpStatus.BAD_REQUEST.value()),
@pasly0920 코드를 U라고 한 만큼 메시지를 `Email` 보다는 `User email`로 시작하는 게 좋을 것 같아요 !

2023-03-21 05:32 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/api/ApplicationApi.java
> +            @PathVariable Season season) {
[Nit] 위 아래의 메서드와 형식이 같지 않아 통일시켜주시는 것도 좋을 것 같아요 !

2023-03-21 05:36 UTC, iju1633 commented
[Nit] application이 없을 시, 모든 답변을 ""로 처리해서 저장하고 있다보니, scheduler를 사용하여 일정 주기별로 비어있는 application을 없애는 것도 좋을 것 같습니다 !

2023-03-21 07:28 UTC, pasly0920 commented on src/main/java/com/gdscuos/recruit/domain/applicant/dao/ApplicationTeamQuestionFindDao.java
> +                    .where(application.user.id.eq(5L), applicationQuestion.team.eq(team))
해당 시즌의 전체 질문을 가지고 있는 ADMIN을 통해 들고 오는 방식인데 어떻게 관리해야할지 조금 고민이네요

2023-03-21 10:59 UTC, pasly0920 commented
@iju1633 수정 완료했습니다

2023-03-21 11:04 UTC, pasly0920 commented
@iju1633 하나만 더 수정해보겠습니다

2023-03-21 13:30 UTC, iju1633 commented on src/main/java/com/gdscuos/recruit/domain/applicant/dao/ApplicationDefaultQuestionFindDao.java
> +    private final Long StorageId = 5L;
@pasly0920 db를 추후에 갈아엎는 것에 대해 방지하기 위해 TODO로 주석을 달아 admin 권한이 있는 유저의 id를 넣을 것 정도의 멘트를 다는 건 어떨까요?

2023-03-22 02:15 UTC, pasly0920 commented
@iju1633 validation 추가하고 말씀해주신 부분도 수정하였습니다.

2023-03-22 02:20 UTC, iju1633 approved these changes
exception 관련해서 구현해놓으신 부분도 제 pr에서 이용해보도록 하겠습니다 ! LGTM 👍 👍

2023-03-22 02:21 UTC, merged